dynhostname: guard against creating a bad CNAME
If the metadata service returns a plain IP instead of the hostname we
asked for (which it's done at least once) we can't use that IP as the
target of a CNAME, so we should just bail.

diff --git a/ansible/roles/dynhostname/templates/dynhostname.j2 b/ansible/roles/dynhostname/templates/dynhostname.j2
--- a/ansible/roles/dynhostname/templates/dynhostname.j2
+++ b/ansible/roles/dynhostname/templates/dynhostname.j2
@@ -16,6 +16,10 @@ publicname=$(curl -fs http://169.254.169.254/latest/meta-data/public-hostname)
 if [[ -z $publicname ]]; then
     publicname=$(curl -fs http://169.254.169.254/latest/meta-data/local-ipv4)
     rectype=A
+elif [[ ! $publicname =~ 'ec2-' ]]; then
+    # Badly formed response from the metadata API, bail.
+    echo "Failed to fetch AWS hostname from metadata, not setting hostname"
+    exit 1
 fi
 
 sethostname() {
