Temporary changes for rollout

diff --git a/ansible/roles/mx/files/80_spamassassin b/ansible/roles/mx/files/80_spamassassin
--- a/ansible/roles/mx/files/80_spamassassin
+++ b/ansible/roles/mx/files/80_spamassassin
@@ -1,41 +1,33 @@
 #!/bin/dash
 
 if check_dfile; then
-    spamscore=$(spamc -c -s 1048576 <$SIMTA_DFILE 2>/dev/null)
-    spamret=$?
-    spamscore=${spamscore%/*}
+    # $load1 is from 75_load
+    if [ ${load1%.*} -lt 30 ]; then
+        spamscore=$(spamc -c -s 1048576 <$SIMTA_DFILE 2>/dev/null)
+        spamret=$?
+        spamscore=${spamscore%/*}
 
-    case $spamret in
-    0)
-        log "80_spamassassin: score $spamscore : pass"
-        ;;
-    1)
-        if ! simrbl -q -l spamassassin-reject.dnsbl "$SIMTA_REMOTE_IP"; then
-            log "80_spamassassin: score $spamscore : reject"
-            filter_exit $MESSAGE_REJECT
-        fi
-        if [ ${spamscore%.*} -gt 10 ] ; then
-            log "80_spamassassin: score $spamscore : reject"
-            filter_exit $MESSAGE_REJECT
-        fi
-        # PENALTYBOX_PASS is from 70_pb
-        if [ $PENALTYBOX_PASS -eq 1 ] ; then
-            log "80_spamassassin: score $spamscore : penaltybox"
-            logmsg=$($penaltybox_bin $penaltybox_args "spamassassin")
-            pbret=$?
-            if [ x"$logmsg" != x ]; then
-                log "80_spamassassin: $logmsg"
+        case $spamret in
+        0)
+            log "80_spamassassin: score $spamscore : pass"
+            ;;
+        1)
+            if ! simrbl -q -l spamassassin-reject.dnsbl "$SIMTA_REMOTE_IP"; then
+                log "80_spamassassin: score $spamscore : reject"
+                filter_exit $MESSAGE_REJECT
             fi
-            if [ $pbret -eq $MESSAGE_TEMPFAIL ]; then
-                filter_exit $MESSAGE_TEMPFAIL
+            if [ ${spamscore%.*} -gt 10 ] ; then
+                log "80_spamassassin: score $spamscore : reject"
+                filter_exit $MESSAGE_REJECT
             fi
-            PENALTYBOX_PASS=0
-        else
-            log "80_spamassassin: score $spamscore : noaction"
-        fi
-        ;;
-    *)
-        log "80_spamassassin: score unknown"
-        ;;
-    esac
+            log "80_spamassassin: score $spamscore : tempfail"
+            filter_exit $MESSAGE_TEMPFAIL
+            ;;
+        *)
+            log "80_spamassassin: score unknown"
+            ;;
+        esac
+    else
+        log "80_spamassassin: scan skipped, load is $load1"
+    fi
 fi
